# -*- coding: utf-8 -*-
"""ConectarConMySQL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3I8tlr-sh4qmaybre0JmK5d1DuwvgLx
"""

# Instalamos el conector MySQL
pip install mysql-connector-python

import mysql.connector # importamos la API
# Creamos el manipulador (handler)  de la conexión
conexion=mysql.connector.connect(
    host="roundhouse.proxy.rlwy.net",
    user="root",
    port=40164,
    password="DTDnejEHBxpDUTvWxkfwQIldCztNChVa",
    database="neptuno_JP")
if conexion.is_connected(): # Comprobamos que la conexión es correcta
  print("La conexión se ha realizado correctamente.")
else:
  print("Ha ocurrido un error de conexión.")

# Instanciamos el asistente de consultas
cursor=conexion.cursor()
# Ejecutamos la consulta deseada
cursor.execute("select * from categorias")
# Recuperamos los datos obtenidos en la consulta
resultado=cursor.fetchall()
# Recorremos la colección recuperando los registros
for fila in resultado:
  print(fila)

# Preguntamos por los valores a insertar
cat=input("IdCategoria:")
nom=input("NombreDeCategoria:")
des=input("Descripcion:")
pb=input("ProductoBasico:")
# Componemos la plantilla de la consulta SQL
sentenciaSQL="insert into categorias (IdCategoria,NombreDeCategoria,Descripcion,ProductoBasico) values (%s,%s,%s,%s)"
# Montamos la tupla a añadir
tupla=(cat,nom,des,pb)
# Combinamos la plantilla con la tupla para ser ejecutada
cursor.execute(sentenciaSQL,tupla)

# Liberamos recursos
cursor.close()
# Damos orden de guardar el resultado en la BBDD (persistencia)
conexion.commit()

import pandas as pd
resultadoDF=pd.read_sql("select * from productos",conexion)
resultadoDF.tail(3)

resultadoDF[resultadoDF['IdCategoria']==1].count()