# -*- coding: utf-8 -*-
"""webScraping DIA.ES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wwcsQRgR_6-Nhvef8SKTwHDC29CsS6cn
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

url="https://www.dia.es"
respuesta=requests.get(url)
html=respuesta.text
dom = BeautifulSoup(html, 'html.parser')
lista=pd.DataFrame(columns=['producto','precio'])

li=dom.find_all('li',class_='carrousel__item')
for elemento_li in li:
  fragmento=str(elemento_li.contents[0])
  dom=BeautifulSoup(fragmento, 'html.parser')
  producto=dom.find('p',class_='search-product-card__product-name')
  precio=dom.find('p',class_='search-product-card__active-price')
  if producto:
    lista.loc[len(lista)]=[producto.getText(),precio.getText()]
    #print(producto.getText(),precio.getText())

print(lista)